# Generated by Django 2.0.2 on 2020-02-05 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=50)),
                ('mendeley_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('dropbox_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_profile',
            },
        ),
    ]
